INSERT INTO public.roles (descripcion, activo)
VALUES ('SUPERADMIN', TRUE)
ON CONFLICT (descripcion) DO NOTHING;

ALTER TABLE public.usuarios
    ADD COLUMN auth_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN password_changed_at TIMESTAMPTZ,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE public.refresh_sessions (
    id UUID PRIMARY KEY,
    family_id UUID NOT NULL,
    usuario_id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    auth_version BIGINT NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoke_reason VARCHAR(100),
    replaced_by_id UUID,
    user_agent_hash CHAR(64),
    ip_hash CHAR(64),
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_refresh_tiempos CHECK (expires_at > issued_at),
    CONSTRAINT fk_refresh_usuario FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT fk_refresh_reemplazo FOREIGN KEY (replaced_by_id)
        REFERENCES public.refresh_sessions(id) ON DELETE RESTRICT
);

CREATE INDEX ix_refresh_usuario_activa
    ON public.refresh_sessions (usuario_id, expires_at)
    WHERE revoked_at IS NULL;

CREATE INDEX ix_refresh_replaced_by ON public.refresh_sessions (replaced_by_id);

CREATE TABLE public.bootstrap_ejecuciones (
    tipo VARCHAR(50) PRIMARY KEY,
    usuario_id BIGINT,
    ejecutado_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bootstrap_usuario FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_bootstrap_usuario ON public.bootstrap_ejecuciones (usuario_id);

CREATE TABLE public.auditoria_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(30) NOT NULL,
    accion VARCHAR(100) NOT NULL,
    entidad_tipo VARCHAR(100),
    entidad_id VARCHAR(100),
    actor_usuario_id BIGINT,
    actor_username_snapshot VARCHAR(100),
    actor_role_snapshot VARCHAR(50),
    ocurrido_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_negocio DATE NOT NULL,
    correlation_id UUID,
    idempotency_key VARCHAR(150),
    estado_anterior JSONB,
    estado_nuevo JSONB,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT ck_auditoria_categoria CHECK (categoria IN (
        'SEGURIDAD', 'USUARIOS', 'TARIFAS', 'FACTURACION',
        'PAGOS', 'CAJA', 'STOCK', 'SISTEMA'
    )),
    CONSTRAINT fk_auditoria_actor FOREIGN KEY (actor_usuario_id)
        REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_auditoria_idempotency
    ON public.auditoria_eventos (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX ix_auditoria_entidad
    ON public.auditoria_eventos (entidad_tipo, entidad_id, ocurrido_at DESC);

CREATE INDEX ix_auditoria_actor
    ON public.auditoria_eventos (actor_usuario_id, ocurrido_at DESC);

CREATE FUNCTION public.rechazar_mutacion_auditoria()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'auditoria_eventos es append-only' USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_auditoria_eventos_append_only
BEFORE UPDATE OR DELETE ON public.auditoria_eventos
FOR EACH ROW EXECUTE FUNCTION public.rechazar_mutacion_auditoria();
