CREATE TABLE public.disciplina_tarifas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disciplina_id BIGINT NOT NULL,
    vigente_desde DATE NOT NULL,
    valor_cuota NUMERIC(19,2) NOT NULL,
    matricula NUMERIC(19,2) NOT NULL DEFAULT 0,
    clase_suelta NUMERIC(19,2) NOT NULL DEFAULT 0,
    clase_prueba NUMERIC(19,2) NOT NULL DEFAULT 0,
    motivo VARCHAR(500) NOT NULL,
    creada_por_usuario_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_disciplina_tarifas_inicio UNIQUE (disciplina_id, vigente_desde),
    CONSTRAINT ck_disciplina_tarifas_importes CHECK (
        valor_cuota >= 0 AND matricula >= 0 AND clase_suelta >= 0 AND clase_prueba >= 0
    ),
    CONSTRAINT fk_disciplina_tarifa_disciplina FOREIGN KEY (disciplina_id)
        REFERENCES public.disciplinas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_disciplina_tarifa_usuario FOREIGN KEY (creada_por_usuario_id)
        REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_disciplina_tarifas_vigencia
    ON public.disciplina_tarifas (disciplina_id, vigente_desde DESC);

CREATE INDEX ix_disciplina_tarifas_usuario
    ON public.disciplina_tarifas (creada_por_usuario_id);

CREATE TABLE public.inscripcion_condiciones_economicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcion_id BIGINT NOT NULL,
    vigente_desde DATE NOT NULL,
    costo_particular NUMERIC(19,2),
    bonificacion_id BIGINT,
    bonificacion_descripcion_snapshot VARCHAR(150),
    bonificacion_porcentaje_snapshot NUMERIC(7,4) NOT NULL DEFAULT 0,
    bonificacion_valor_fijo_snapshot NUMERIC(19,2) NOT NULL DEFAULT 0,
    motivo VARCHAR(500) NOT NULL,
    creada_por_usuario_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_inscripcion_condicion_inicio UNIQUE (inscripcion_id, vigente_desde),
    CONSTRAINT ck_inscripcion_condicion_importes CHECK (
        (costo_particular IS NULL OR costo_particular >= 0)
        AND bonificacion_porcentaje_snapshot BETWEEN 0 AND 100
        AND bonificacion_valor_fijo_snapshot >= 0
    ),
    CONSTRAINT fk_condicion_inscripcion FOREIGN KEY (inscripcion_id)
        REFERENCES public.inscripciones(id) ON DELETE RESTRICT,
    CONSTRAINT fk_condicion_bonificacion FOREIGN KEY (bonificacion_id)
        REFERENCES public.bonificaciones(id) ON DELETE RESTRICT,
    CONSTRAINT fk_condicion_usuario FOREIGN KEY (creada_por_usuario_id)
        REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_condiciones_inscripcion_vigencia
    ON public.inscripcion_condiciones_economicas (inscripcion_id, vigente_desde DESC);

CREATE INDEX ix_condiciones_bonificacion
    ON public.inscripcion_condiciones_economicas (bonificacion_id);

CREATE INDEX ix_condiciones_usuario
    ON public.inscripcion_condiciones_economicas (creada_por_usuario_id);
