CREATE TABLE public.cargo_liquidaciones (
    cargo_id BIGINT PRIMARY KEY,
    periodo_desde DATE NOT NULL,
    tarifa_disciplina_id BIGINT,
    condicion_inscripcion_id BIGINT,
    origen_precio VARCHAR(30) NOT NULL,
    importe_base NUMERIC(19,2) NOT NULL,
    descuento_porcentaje NUMERIC(7,4) NOT NULL DEFAULT 0,
    descuento_importe NUMERIC(19,2) NOT NULL DEFAULT 0,
    recargo_porcentaje NUMERIC(7,4) NOT NULL DEFAULT 0,
    recargo_importe NUMERIC(19,2) NOT NULL DEFAULT 0,
    importe_final NUMERIC(19,2) NOT NULL,
    formula_version INTEGER NOT NULL,
    observaciones VARCHAR(500),
    calculada_por_usuario_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_cargo_liquidacion_origen CHECK (origen_precio IN (
        'TARIFA_HISTORICA', 'COSTO_PARTICULAR', 'MANUAL_HISTORICO', 'MIGRADO_CARGO_EXISTENTE'
    )),
    CONSTRAINT ck_cargo_liquidacion_importes CHECK (
        importe_base >= 0
        AND descuento_porcentaje BETWEEN 0 AND 100
        AND descuento_importe >= 0
        AND recargo_porcentaje BETWEEN 0 AND 100
        AND recargo_importe >= 0
        AND importe_final >= 0
    ),
    CONSTRAINT fk_liquidacion_cargo FOREIGN KEY (cargo_id)
        REFERENCES public.cargos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_liquidacion_tarifa FOREIGN KEY (tarifa_disciplina_id)
        REFERENCES public.disciplina_tarifas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_liquidacion_condicion FOREIGN KEY (condicion_inscripcion_id)
        REFERENCES public.inscripcion_condiciones_economicas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_liquidacion_usuario FOREIGN KEY (calculada_por_usuario_id)
        REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_liquidaciones_tarifa ON public.cargo_liquidaciones (tarifa_disciplina_id);
CREATE INDEX ix_liquidaciones_condicion ON public.cargo_liquidaciones (condicion_inscripcion_id);
CREATE INDEX ix_liquidaciones_usuario ON public.cargo_liquidaciones (calculada_por_usuario_id);

CREATE TABLE public.cargo_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo_id BIGINT NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    estado_anterior VARCHAR(10),
    estado_nuevo VARCHAR(10),
    saldo_anterior NUMERIC(19,2),
    saldo_nuevo NUMERIC(19,2),
    referencia_tipo VARCHAR(30),
    referencia_id BIGINT,
    idempotency_key VARCHAR(150) NOT NULL,
    usuario_id BIGINT,
    ocurrido_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correlation_id UUID,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_cargo_evento_idempotency UNIQUE (idempotency_key),
    CONSTRAINT ck_cargo_evento_tipo CHECK (tipo IN (
        'EMITIDO', 'PAGO_APLICADO', 'PAGO_REVERTIDO', 'CREDITO_APLICADO',
        'CREDITO_REVERTIDO', 'RECARGO_CREADO', 'ANULADO'
    )),
    CONSTRAINT fk_cargo_evento_cargo FOREIGN KEY (cargo_id)
        REFERENCES public.cargos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cargo_evento_usuario FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_cargo_eventos_cargo_fecha ON public.cargo_eventos (cargo_id, ocurrido_at, id);
CREATE INDEX ix_cargo_eventos_usuario ON public.cargo_eventos (usuario_id);

INSERT INTO public.cargo_liquidaciones(
    cargo_id, periodo_desde, origen_precio, importe_base, importe_final,
    formula_version, observaciones, created_at)
SELECT c.id,
       COALESCE(
           make_date(m.anio, m.mes, 1),
           make_date(mo.anio, mo.mes, 1),
           make_date(ma.anio, 1, 1),
           date_trunc('month', c.fecha_emision)::date
       ),
       'MIGRADO_CARGO_EXISTENTE',
       c.importe_original,
       c.importe_original,
       0,
       'Backfill conservador V4: sólo se conoce el importe original definitivo.',
       c.created_at
FROM public.cargos c
LEFT JOIN public.mensualidades m ON m.id = c.mensualidad_id
LEFT JOIN public.cargos origen ON origen.id = c.cargo_origen_id
LEFT JOIN public.mensualidades mo ON mo.id = origen.mensualidad_id
LEFT JOIN public.matriculas ma ON ma.id = c.matricula_id;

WITH pagos AS (
    SELECT cargo_id, sum(importe_aplicado) AS importe
    FROM public.aplicaciones_pago WHERE estado = 'APLICADA' GROUP BY cargo_id
), credito AS (
    SELECT cargo_id, sum(importe) AS importe
    FROM (
        SELECT cargo_id, importe FROM public.movimientos_credito WHERE tipo = 'CONSUMO'
        UNION ALL
        SELECT original.cargo_id, -reverso.importe
        FROM public.movimientos_credito reverso
        JOIN public.movimientos_credito original ON original.id = reverso.movimiento_revertido_id
        WHERE reverso.tipo = 'REVERSO' AND original.tipo = 'CONSUMO'
    ) neto GROUP BY cargo_id
)
INSERT INTO public.cargo_eventos(
    cargo_id, tipo, estado_nuevo, saldo_nuevo, idempotency_key, ocurrido_at, metadata)
SELECT c.id, 'EMITIDO', c.estado,
       c.importe_original - coalesce(p.importe, 0) - coalesce(cr.importe, 0),
       'migration:v4:cargo:' || c.id || ':emitido', c.created_at,
       jsonb_build_object('origen', 'MIGRADO_CARGO_EXISTENTE')
FROM public.cargos c
LEFT JOIN pagos p ON p.cargo_id = c.id
LEFT JOIN credito cr ON cr.cargo_id = c.id;

CREATE FUNCTION public.rechazar_mutacion_cargo_evento()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'cargo_eventos es append-only' USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_cargo_eventos_append_only
BEFORE UPDATE OR DELETE ON public.cargo_eventos
FOR EACH ROW EXECUTE FUNCTION public.rechazar_mutacion_cargo_evento();

CREATE VIEW public.v_cuotas_seguimiento AS
WITH pagos AS (
    SELECT cargo_id, sum(importe_aplicado) AS aplicado, max(fecha) AS ultima_fecha
    FROM public.aplicaciones_pago WHERE estado = 'APLICADA' GROUP BY cargo_id
), credito AS (
    SELECT cargo_id, sum(importe) AS aplicado, max(fecha) AS ultima_fecha
    FROM (
        SELECT cargo_id, importe, created_at::date AS fecha
        FROM public.movimientos_credito WHERE tipo = 'CONSUMO'
        UNION ALL
        SELECT original.cargo_id, -reverso.importe, reverso.created_at::date
        FROM public.movimientos_credito reverso
        JOIN public.movimientos_credito original ON original.id = reverso.movimiento_revertido_id
        WHERE reverso.tipo = 'REVERSO' AND original.tipo = 'CONSUMO'
    ) neto GROUP BY cargo_id
), cargos_saldo AS (
    SELECT c.*,
           coalesce(p.aplicado, 0) AS aplicado_pagos,
           coalesce(cr.aplicado, 0) AS aplicado_credito,
           c.importe_original - coalesce(p.aplicado, 0) - coalesce(cr.aplicado, 0) AS saldo,
           greatest(p.ultima_fecha, cr.ultima_fecha) AS ultima_fecha_aplicacion
    FROM public.cargos c
    LEFT JOIN pagos p ON p.cargo_id = c.id
    LEFT JOIN credito cr ON cr.cargo_id = c.id
), recargos AS (
    SELECT r.cargo_origen_id,
           sum(r.importe_original) AS importe_original,
           sum(r.saldo) AS saldo
    FROM cargos_saldo r WHERE r.tipo = 'RECARGO' GROUP BY r.cargo_origen_id
)
SELECT c.id AS cargo_id,
       i.alumno_id,
       concat_ws(' ', a.nombre, a.apellido) AS alumno,
       i.id AS inscripcion_id,
       i.disciplina_id,
       d.nombre AS disciplina,
       m.anio,
       m.mes,
       m.fecha_generacion,
       m.fecha_vencimiento,
       l.tarifa_disciplina_id,
       td.valor_cuota AS tarifa_utilizada,
       l.importe_base,
       l.descuento_porcentaje,
       l.descuento_importe,
       c.importe_original,
       c.aplicado_pagos,
       c.aplicado_credito,
       c.saldo AS saldo_cuota,
       coalesce(r.importe_original, 0) AS recargos_vinculados,
       coalesce(r.saldo, 0) AS saldo_recargos,
       c.saldo + coalesce(r.saldo, 0) AS saldo_total_periodo,
       c.estado AS estado_persistido,
       CASE WHEN c.estado = 'ANULADO' THEN 'ANULADO'
            WHEN c.saldo = 0 THEN 'PAGADO'
            WHEN c.saldo < c.importe_original THEN 'PARCIAL'
            ELSE 'PENDIENTE' END AS estado_esperado,
       c.ultima_fecha_aplicacion,
       CASE WHEN c.saldo + coalesce(r.saldo, 0) > 0 AND m.fecha_vencimiento < CURRENT_DATE
            THEN CURRENT_DATE - m.fecha_vencimiento ELSE 0 END AS dias_mora,
       l.origen_precio,
       l.formula_version
FROM cargos_saldo c
JOIN public.mensualidades m ON m.id = c.mensualidad_id
JOIN public.inscripciones i ON i.id = m.inscripcion_id
JOIN public.alumnos a ON a.id = i.alumno_id
JOIN public.disciplinas d ON d.id = i.disciplina_id
JOIN public.cargo_liquidaciones l ON l.cargo_id = c.id
LEFT JOIN public.disciplina_tarifas td ON td.id = l.tarifa_disciplina_id
LEFT JOIN recargos r ON r.cargo_origen_id = c.id
WHERE c.tipo = 'MENSUALIDAD';
