-- V5__base_roles_permissions_seed.sql
-- Refactor RBAC estructural.
-- IMPORTANTE:
-- - Esta migración NO seedear roles.
-- - Esta migración NO seedear permisos.
-- - Esta migración NO asigna permisos a roles.
-- - El backfill usuarios.rol_id -> usuario_roles NO es seed: es compatibilidad transicional.
--
-- Requiere:
-- - V1: public.roles, public.usuarios.
-- - V2: usuarios.auth_version.

-- ============================================================
-- 1. Extensión estructural de roles legacy
-- ============================================================

ALTER TABLE public.roles
    ADD COLUMN codigo VARCHAR(50),
    ADD COLUMN nombre VARCHAR(100),
    ADD COLUMN descripcion_funcional VARCHAR(255),
    ADD COLUMN sistema BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN editable BOOLEAN NOT NULL DEFAULT TRUE;

-- Backfill técnico desde roles.descripcion.
-- No crea roles nuevos. Sólo completa columnas nuevas para roles existentes.
WITH base AS (
    SELECT
        id,
        descripcion,
        COALESCE(
                NULLIF(
                        regexp_replace(upper(btrim(descripcion)), '[^A-Z0-9]+', '_', 'g'),
                        ''
                ),
                'ROL_' || id::text
        ) AS codigo_base
    FROM public.roles
),
     normalizado AS (
         SELECT
             id,
             descripcion,
             CASE
                 WHEN codigo_base ~ '^[A-Z]' THEN codigo_base
                 ELSE 'ROL_' || codigo_base
                 END AS codigo_preparado
         FROM base
     ),
     final AS (
         SELECT
             id,
             descripcion,
             CASE
                 WHEN length(codigo_preparado) < 3 THEN rpad(codigo_preparado, 3, '_')
                 ELSE left(codigo_preparado, 50)
END AS codigo_final
    FROM normalizado
)
UPDATE public.roles r
SET codigo = f.codigo_final,
    nombre = COALESCE(NULLIF(btrim(r.nombre), ''), btrim(r.descripcion), f.codigo_final),
    descripcion_funcional = COALESCE(
            NULLIF(btrim(r.descripcion_funcional), ''),
            NULLIF(btrim(r.descripcion), ''),
            f.codigo_final
                            ),
    sistema = f.codigo_final IN ('SUPERADMIN', 'ADMINISTRADOR'),
    editable = f.codigo_final <> 'SUPERADMIN'
    FROM final f
WHERE r.id = f.id
  AND (
    r.codigo IS NULL
   OR r.nombre IS NULL
   OR r.descripcion_funcional IS NULL
    );

ALTER TABLE public.roles
    ALTER COLUMN codigo SET NOT NULL,
ALTER COLUMN nombre SET NOT NULL;

ALTER TABLE public.roles
    ADD CONSTRAINT uq_roles_codigo UNIQUE (codigo),
    ADD CONSTRAINT ck_roles_codigo_formato CHECK (codigo ~ '^[A-Z][A-Z0-9_]{2,49}$');

CREATE INDEX ix_roles_activo_codigo
    ON public.roles (activo, codigo);

CREATE INDEX ix_roles_sistema
    ON public.roles (sistema);

-- ============================================================
-- 2. Tabla de permisos
-- ============================================================

CREATE TABLE public.permisos (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 codigo VARCHAR(100) NOT NULL,
                                 descripcion VARCHAR(255) NOT NULL,
                                 modulo VARCHAR(50) NOT NULL,
                                 activo BOOLEAN NOT NULL DEFAULT TRUE,
                                 sistema BOOLEAN NOT NULL DEFAULT TRUE,
                                 CONSTRAINT uq_permisos_codigo UNIQUE (codigo),
                                 CONSTRAINT ck_permisos_codigo_formato CHECK (codigo ~ '^PERM_[A-Z0-9_]{3,95}$'),
    CONSTRAINT ck_permisos_modulo_formato CHECK (modulo ~ '^[A-Z][A-Z0-9_]{1,49}$')
);

CREATE INDEX ix_permisos_modulo_activo
    ON public.permisos (modulo, activo);

CREATE INDEX ix_permisos_activo_codigo
    ON public.permisos (activo, codigo);

-- ============================================================
-- 3. Relación roles-permisos
-- ============================================================

CREATE TABLE public.rol_permisos (
                                     rol_id BIGINT NOT NULL,
                                     permiso_id BIGINT NOT NULL,
                                     CONSTRAINT pk_rol_permisos PRIMARY KEY (rol_id, permiso_id),
                                     CONSTRAINT fk_rol_permisos_rol FOREIGN KEY (rol_id)
                                         REFERENCES public.roles(id) ON DELETE CASCADE,
                                     CONSTRAINT fk_rol_permisos_permiso FOREIGN KEY (permiso_id)
                                         REFERENCES public.permisos(id) ON DELETE RESTRICT
);

CREATE INDEX ix_rol_permisos_permiso
    ON public.rol_permisos (permiso_id);

-- ============================================================
-- 4. Relación usuarios-roles
-- ============================================================

CREATE TABLE public.usuario_roles (
                                      usuario_id BIGINT NOT NULL,
                                      rol_id BIGINT NOT NULL,
                                      asignado_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      asignado_por_usuario_id BIGINT,
                                      CONSTRAINT pk_usuario_roles PRIMARY KEY (usuario_id, rol_id),
                                      CONSTRAINT fk_usuario_roles_usuario FOREIGN KEY (usuario_id)
                                          REFERENCES public.usuarios(id) ON DELETE CASCADE,
                                      CONSTRAINT fk_usuario_roles_rol FOREIGN KEY (rol_id)
                                          REFERENCES public.roles(id) ON DELETE RESTRICT,
                                      CONSTRAINT fk_usuario_roles_asignado_por FOREIGN KEY (asignado_por_usuario_id)
                                          REFERENCES public.usuarios(id) ON DELETE SET NULL
);

CREATE INDEX ix_usuario_roles_rol
    ON public.usuario_roles (rol_id);

CREATE INDEX ix_usuario_roles_asignado_por
    ON public.usuario_roles (asignado_por_usuario_id);

-- Backfill de compatibilidad:
-- conserva el rol principal legacy usuarios.rol_id como primer rol efectivo.
INSERT INTO public.usuario_roles (usuario_id, rol_id)
SELECT id, rol_id
FROM public.usuarios
WHERE rol_id IS NOT NULL
    ON CONFLICT (usuario_id, rol_id) DO NOTHING;

-- ============================================================
-- 5. Inmutabilidad de códigos técnicos
-- ============================================================

CREATE OR REPLACE FUNCTION public.impedir_cambio_codigo_roles()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.codigo <> OLD.codigo THEN
        RAISE EXCEPTION 'roles.codigo es inmutable' USING ERRCODE = '55000';
END IF;

RETURN NEW;
END;
$$;

CREATE TRIGGER trg_roles_codigo_inmutable
    BEFORE UPDATE ON public.roles
    FOR EACH ROW
    EXECUTE FUNCTION public.impedir_cambio_codigo_roles();

CREATE OR REPLACE FUNCTION public.impedir_cambio_codigo_permisos()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.codigo <> OLD.codigo THEN
        RAISE EXCEPTION 'permisos.codigo es inmutable' USING ERRCODE = '55000';
END IF;

RETURN NEW;
END;
$$;

CREATE TRIGGER trg_permisos_codigo_inmutable
    BEFORE UPDATE ON public.permisos
    FOR EACH ROW
    EXECUTE FUNCTION public.impedir_cambio_codigo_permisos();

-- ============================================================
-- 6. Invalidación de tokens/sesiones por cambio de modelo RBAC
-- ============================================================

UPDATE public.usuarios
SET auth_version = auth_version + 1;