CREATE TABLE public.permisos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    modulo VARCHAR(50) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    sistema BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_permisos_codigo UNIQUE (codigo)
);

ALTER TABLE public.roles
    ADD COLUMN codigo VARCHAR(50),
    ADD COLUMN nombre VARCHAR(100),
    ADD COLUMN descripcion_funcional VARCHAR(255),
    ADD COLUMN sistema BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN editable BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE public.roles
SET codigo = upper(descripcion),
    nombre = descripcion
WHERE codigo IS NULL OR nombre IS NULL;

ALTER TABLE public.roles
    ALTER COLUMN codigo SET NOT NULL,
    ALTER COLUMN nombre SET NOT NULL;

CREATE UNIQUE INDEX uq_roles_codigo_normalizado ON public.roles (upper(codigo));

CREATE TABLE public.usuario_roles (
    usuario_id BIGINT NOT NULL,
    rol_id BIGINT NOT NULL,
    asignado_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    asignado_por_usuario_id BIGINT,
    CONSTRAINT pk_usuario_roles PRIMARY KEY (usuario_id, rol_id),
    CONSTRAINT fk_usuario_roles_usuario FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT fk_usuario_roles_rol FOREIGN KEY (rol_id)
        REFERENCES public.roles(id) ON DELETE RESTRICT,
    CONSTRAINT fk_usuario_roles_asignado_por FOREIGN KEY (asignado_por_usuario_id)
        REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_usuario_roles_rol ON public.usuario_roles (rol_id);
CREATE INDEX ix_usuario_roles_asignado_por ON public.usuario_roles (asignado_por_usuario_id);

CREATE TABLE public.rol_permisos (
    rol_id BIGINT NOT NULL,
    permiso_id BIGINT NOT NULL,
    CONSTRAINT pk_rol_permisos PRIMARY KEY (rol_id, permiso_id),
    CONSTRAINT fk_rol_permisos_rol FOREIGN KEY (rol_id)
        REFERENCES public.roles(id) ON DELETE RESTRICT,
    CONSTRAINT fk_rol_permisos_permiso FOREIGN KEY (permiso_id)
        REFERENCES public.permisos(id) ON DELETE RESTRICT
);

CREATE INDEX ix_rol_permisos_permiso ON public.rol_permisos (permiso_id);

INSERT INTO public.usuario_roles (usuario_id, rol_id)
SELECT id, rol_id
FROM public.usuarios
ON CONFLICT (usuario_id, rol_id) DO NOTHING;

INSERT INTO public.permisos (codigo, descripcion, modulo) VALUES
    ('USUARIOS_READ', 'Consultar usuarios', 'SEGURIDAD'),
    ('USUARIOS_WRITE', 'Administrar usuarios', 'SEGURIDAD'),
    ('ROLES_READ', 'Consultar roles', 'SEGURIDAD'),
    ('ROLES_WRITE', 'Administrar roles y sus permisos', 'SEGURIDAD'),
    ('PERMISOS_READ', 'Consultar permisos', 'SEGURIDAD'),
    ('AUDITORIA_READ', 'Consultar auditoría de seguridad', 'SEGURIDAD'),
    ('ALUMNOS_READ', 'Consultar alumnos', 'ALUMNOS'),
    ('ALUMNOS_WRITE', 'Administrar alumnos', 'ALUMNOS'),
    ('PROFESORES_READ', 'Consultar profesores', 'ACADEMICO'),
    ('PROFESORES_WRITE', 'Administrar profesores', 'ACADEMICO'),
    ('DISCIPLINAS_READ', 'Consultar disciplinas', 'ACADEMICO'),
    ('DISCIPLINAS_WRITE', 'Administrar disciplinas', 'ACADEMICO'),
    ('INSCRIPCIONES_READ', 'Consultar inscripciones', 'ACADEMICO'),
    ('INSCRIPCIONES_WRITE', 'Administrar inscripciones', 'ACADEMICO'),
    ('ASISTENCIAS_READ', 'Consultar asistencias', 'ACADEMICO'),
    ('ASISTENCIAS_WRITE', 'Administrar asistencias', 'ACADEMICO'),
    ('PAGOS_READ', 'Consultar pagos', 'FINANZAS'),
    ('PAGOS_WRITE', 'Registrar pagos', 'FINANZAS'),
    ('PAGOS_ANULAR', 'Anular pagos', 'FINANZAS'),
    ('CAJA_READ', 'Consultar caja', 'FINANZAS'),
    ('EGRESOS_READ', 'Consultar egresos', 'FINANZAS'),
    ('EGRESOS_WRITE', 'Registrar egresos', 'FINANZAS'),
    ('EGRESOS_ANULAR', 'Anular egresos', 'FINANZAS'),
    ('CARGOS_READ', 'Consultar cargos', 'FINANZAS'),
    ('CARGOS_WRITE', 'Administrar cargos', 'FINANZAS'),
    ('CREDITOS_READ', 'Consultar créditos', 'FINANZAS'),
    ('CREDITOS_WRITE', 'Administrar créditos', 'FINANZAS'),
    ('CONCEPTOS_READ', 'Consultar conceptos', 'CATALOGOS'),
    ('CONCEPTOS_WRITE', 'Administrar conceptos', 'CATALOGOS'),
    ('BONIFICACIONES_READ', 'Consultar bonificaciones', 'CATALOGOS'),
    ('BONIFICACIONES_WRITE', 'Administrar bonificaciones', 'CATALOGOS'),
    ('RECARGOS_READ', 'Consultar recargos', 'CATALOGOS'),
    ('RECARGOS_WRITE', 'Administrar recargos', 'CATALOGOS'),
    ('METODOS_PAGO_READ', 'Consultar métodos de pago', 'CATALOGOS'),
    ('METODOS_PAGO_WRITE', 'Administrar métodos de pago', 'CATALOGOS'),
    ('STOCK_READ', 'Consultar stock', 'CATALOGOS'),
    ('STOCK_WRITE', 'Administrar stock', 'CATALOGOS'),
    ('REPORTES_READ', 'Consultar reportes', 'REPORTES'),
    ('REPORTES_EXPORT', 'Exportar reportes', 'REPORTES')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO public.roles (
    descripcion, activo, codigo, nombre, descripcion_funcional, sistema, editable
) VALUES
    ('SUPERADMIN', TRUE, 'SUPERADMIN', 'Superadministrador', 'Administración total del sistema', TRUE, FALSE),
    ('ADMINISTRADOR', TRUE, 'ADMINISTRADOR', 'Administrador', 'Administración operativa', TRUE, FALSE),
    ('RECEPCION', TRUE, 'RECEPCION', 'Recepción', 'Gestión de recepción y asistencia', TRUE, FALSE),
    ('COBRANZAS', TRUE, 'COBRANZAS', 'Cobranzas', 'Gestión de cobranzas y caja', TRUE, FALSE),
    ('PROFESOR', TRUE, 'PROFESOR', 'Profesor', 'Consulta académica y registro de asistencias', TRUE, FALSE),
    ('LECTURA', TRUE, 'LECTURA', 'Lectura', 'Acceso de consulta', TRUE, FALSE)
ON CONFLICT (descripcion) DO NOTHING;

UPDATE public.roles
SET codigo = upper(descripcion),
    nombre = CASE upper(descripcion)
        WHEN 'SUPERADMIN' THEN 'Superadministrador'
        WHEN 'ADMINISTRADOR' THEN 'Administrador'
        WHEN 'RECEPCION' THEN 'Recepción'
        WHEN 'COBRANZAS' THEN 'Cobranzas'
        WHEN 'PROFESOR' THEN 'Profesor'
        WHEN 'LECTURA' THEN 'Lectura'
    END,
    sistema = TRUE,
    editable = FALSE
WHERE upper(descripcion) IN ('SUPERADMIN', 'ADMINISTRADOR', 'RECEPCION', 'COBRANZAS', 'PROFESOR', 'LECTURA');

INSERT INTO public.rol_permisos (rol_id, permiso_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permisos p
WHERE r.codigo = 'SUPERADMIN'
ON CONFLICT (rol_id, permiso_id) DO NOTHING;

INSERT INTO public.rol_permisos (rol_id, permiso_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permisos p
WHERE r.codigo = 'ADMINISTRADOR' AND p.modulo <> 'SEGURIDAD'
ON CONFLICT (rol_id, permiso_id) DO NOTHING;

INSERT INTO public.rol_permisos (rol_id, permiso_id)
SELECT r.id, p.id
FROM public.roles r
JOIN public.permisos p ON p.codigo = ANY (ARRAY[
    'ALUMNOS_READ', 'ALUMNOS_WRITE',
    'INSCRIPCIONES_READ', 'INSCRIPCIONES_WRITE',
    'ASISTENCIAS_READ', 'ASISTENCIAS_WRITE',
    'DISCIPLINAS_READ', 'PROFESORES_READ',
    'CONCEPTOS_READ', 'BONIFICACIONES_READ', 'RECARGOS_READ',
    'METODOS_PAGO_READ', 'STOCK_READ'
])
WHERE r.codigo = 'RECEPCION'
ON CONFLICT (rol_id, permiso_id) DO NOTHING;

INSERT INTO public.rol_permisos (rol_id, permiso_id)
SELECT r.id, p.id
FROM public.roles r
JOIN public.permisos p ON p.codigo = ANY (ARRAY[
    'PAGOS_READ', 'PAGOS_WRITE', 'PAGOS_ANULAR', 'CAJA_READ',
    'CARGOS_READ', 'CARGOS_WRITE', 'CREDITOS_READ', 'CREDITOS_WRITE',
    'EGRESOS_READ', 'EGRESOS_WRITE', 'EGRESOS_ANULAR',
    'ALUMNOS_READ', 'REPORTES_READ', 'REPORTES_EXPORT'
])
WHERE r.codigo = 'COBRANZAS'
ON CONFLICT (rol_id, permiso_id) DO NOTHING;

INSERT INTO public.rol_permisos (rol_id, permiso_id)
SELECT r.id, p.id
FROM public.roles r
JOIN public.permisos p ON p.codigo = ANY (ARRAY[
    'ALUMNOS_READ', 'DISCIPLINAS_READ', 'ASISTENCIAS_READ', 'ASISTENCIAS_WRITE'
])
WHERE r.codigo = 'PROFESOR'
ON CONFLICT (rol_id, permiso_id) DO NOTHING;

INSERT INTO public.rol_permisos (rol_id, permiso_id)
SELECT r.id, p.id
FROM public.roles r
JOIN public.permisos p ON right(p.codigo, 5) = '_READ'
WHERE r.codigo = 'LECTURA'
ON CONFLICT (rol_id, permiso_id) DO NOTHING;
