ALTER TABLE public.roles
    ADD COLUMN codigo VARCHAR(50),
    ADD COLUMN nombre VARCHAR(100),
    ADD COLUMN descripcion_funcional VARCHAR(255),
    ADD COLUMN sistema BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN editable BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE public.roles
SET codigo = upper(descripcion),
    nombre = descripcion,
    descripcion_funcional = descripcion,
    sistema = upper(descripcion) IN ('SUPERADMIN', 'ADMINISTRADOR'),
    editable = upper(descripcion) NOT IN ('SUPERADMIN');

ALTER TABLE public.roles
    ALTER COLUMN codigo SET NOT NULL,
    ALTER COLUMN nombre SET NOT NULL;

ALTER TABLE public.roles
    ADD CONSTRAINT uq_roles_codigo UNIQUE (codigo),
    ADD CONSTRAINT ck_roles_codigo_formato CHECK (codigo ~ '^[A-Z][A-Z0-9_]{2,49}$');

CREATE TABLE public.permisos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    modulo VARCHAR(50) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    sistema BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_permisos_codigo UNIQUE (codigo),
    CONSTRAINT ck_permisos_codigo_formato CHECK (codigo ~ '^PERM_[A-Z0-9_]{3,95}$')
);

CREATE TABLE public.rol_permisos (
    rol_id BIGINT NOT NULL,
    permiso_id BIGINT NOT NULL,
    CONSTRAINT pk_rol_permisos PRIMARY KEY (rol_id, permiso_id),
    CONSTRAINT fk_rol_permisos_rol FOREIGN KEY (rol_id) REFERENCES public.roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_rol_permisos_permiso FOREIGN KEY (permiso_id) REFERENCES public.permisos(id) ON DELETE RESTRICT
);

CREATE INDEX ix_rol_permisos_permiso ON public.rol_permisos (permiso_id);

CREATE TABLE public.usuario_roles (
    usuario_id BIGINT NOT NULL,
    rol_id BIGINT NOT NULL,
    CONSTRAINT pk_usuario_roles PRIMARY KEY (usuario_id, rol_id),
    CONSTRAINT fk_usuario_roles_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_roles_rol FOREIGN KEY (rol_id) REFERENCES public.roles(id) ON DELETE RESTRICT
);

CREATE INDEX ix_usuario_roles_rol ON public.usuario_roles (rol_id);

INSERT INTO public.usuario_roles(usuario_id, rol_id)
SELECT id, rol_id
FROM public.usuarios
ON CONFLICT DO NOTHING;

INSERT INTO public.permisos(codigo, descripcion, modulo, activo, sistema)
VALUES
    ('PERM_APP_ACCESO', 'Acceder al panel autenticado', 'SISTEMA', TRUE, TRUE),
    ('PERM_USUARIOS_ADMIN', 'Administrar usuarios', 'SEGURIDAD', TRUE, TRUE),
    ('PERM_ROLES_ADMIN', 'Administrar roles y asignación de permisos', 'SEGURIDAD', TRUE, TRUE),
    ('PERM_AUDITORIA_SEGURIDAD_LEER', 'Consultar auditoría de seguridad', 'SEGURIDAD', TRUE, TRUE),
    ('PERM_TARIFAS_ADMIN', 'Administrar tarifas y condiciones económicas vigentes/futuras', 'TARIFAS', TRUE, TRUE),
    ('PERM_TARIFAS_HISTORICAS', 'Cargar tarifas y condiciones económicas históricas', 'TARIFAS', TRUE, TRUE),
    ('PERM_MENSUALIDADES_GENERAR_MANUAL', 'Generar mensualidades manualmente', 'FACTURACION', TRUE, TRUE),
    ('PERM_FINANZAS_OPERAR', 'Operar pagos, caja, cargos, créditos, egresos y stock financiero', 'FINANZAS', TRUE, TRUE)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO public.rol_permisos(rol_id, permiso_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permisos p
WHERE r.codigo = 'SUPERADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO public.rol_permisos(rol_id, permiso_id)
SELECT r.id, p.id
FROM public.roles r
JOIN public.permisos p ON p.codigo IN (
    'PERM_APP_ACCESO',
    'PERM_TARIFAS_ADMIN',
    'PERM_FINANZAS_OPERAR'
)
WHERE r.codigo = 'ADMINISTRADOR'
ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION public.impedir_cambio_codigo_roles()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.codigo <> OLD.codigo THEN
        RAISE EXCEPTION 'roles.codigo es inmutable' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_roles_codigo_inmutable
BEFORE UPDATE ON public.roles
FOR EACH ROW EXECUTE FUNCTION public.impedir_cambio_codigo_roles();

CREATE OR REPLACE FUNCTION public.impedir_cambio_codigo_permisos()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.codigo <> OLD.codigo THEN
        RAISE EXCEPTION 'permisos.codigo es inmutable' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_permisos_codigo_inmutable
BEFORE UPDATE ON public.permisos
FOR EACH ROW EXECUTE FUNCTION public.impedir_cambio_codigo_permisos();