export const PERMISSIONS = {
  APP_ACCESS: "PERM_APP_ACCESO",

  USUARIOS_ADMIN: "PERM_USUARIOS_ADMIN",
  ROLES_ADMIN: "PERM_ROLES_ADMIN",
  AUDITORIA_SEGURIDAD_LEER: "PERM_AUDITORIA_SEGURIDAD_LEER",

  MENSUALIDADES_GENERAR_MANUAL: "PERM_MENSUALIDADES_GENERAR_MANUAL",

  PAGOS_REGISTRAR: "PERM_PAGOS_REGISTRAR",
  PAGOS_ANULAR: "PERM_PAGOS_ANULAR",

  EGRESOS_ADMIN: "PERM_EGRESOS_ADMIN",

  STOCK_ADMIN: "PERM_STOCK_ADMIN",
  STOCK_VENDER: "PERM_STOCK_VENDER",

  CREDITOS_ADMIN: "PERM_CREDITOS_ADMIN",
  CREDITOS_CONSUMIR: "PERM_CREDITOS_CONSUMIR",

  TARIFAS_ADMIN: "PERM_TARIFAS_ADMIN",
  TARIFAS_HISTORICAS: "PERM_TARIFAS_HISTORICAS",
  CONDICIONES_ECONOMICAS_ADMIN: "PERM_CONDICIONES_ECONOMICAS_ADMIN",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];