export const PERMISSIONS = {
  APP_ACCESS: "PERM_APP_ACCESO",

  USUARIOS_ADMIN: "PERM_USUARIOS_ADMIN",
  ROLES_ADMIN: "PERM_ROLES_ADMIN",
  AUDITORIA_SEGURIDAD_LEER: "PERM_AUDITORIA_SEGURIDAD_LEER",

  MENSUALIDADES_GENERAR_MANUAL: "PERM_MENSUALIDADES_GENERAR_MANUAL",

  PAGOS_REGISTRAR: "PERM_PAGOS_REGISTRAR",
  PAGOS_ANULAR: "PERM_PAGOS_ANULAR",

  EGRESOS_ADMIN: "PERM_EGRESOS_ADMIN",

  STOCK_ADMIN: "PERM_STOCK_ADMIN",
  STOCK_VENDER: "PERM_STOCK_VENDER",

  CREDITOS_ADMIN: "PERM_CREDITOS_ADMIN",
  CREDITOS_CONSUMIR: "PERM_CREDITOS_CONSUMIR",

  TARIFAS_ADMIN: "PERM_TARIFAS_ADMIN",
  TARIFAS_HISTORICAS: "PERM_TARIFAS_HISTORICAS",
  CONDICIONES_ECONOMICAS_ADMIN: "PERM_CONDICIONES_ECONOMICAS_ADMIN",

  ALUMNOS_LEER: "PERM_ALUMNOS_LEER",
  ALUMNOS_ADMIN: "PERM_ALUMNOS_ADMIN",
  INSCRIPCIONES_LEER: "PERM_INSCRIPCIONES_LEER",
  INSCRIPCIONES_ADMIN: "PERM_INSCRIPCIONES_ADMIN",
  DISCIPLINAS_LEER: "PERM_DISCIPLINAS_LEER",
  DISCIPLINAS_ADMIN: "PERM_DISCIPLINAS_ADMIN",
  PROFESORES_LEER: "PERM_PROFESORES_LEER",
  PROFESORES_ADMIN: "PERM_PROFESORES_ADMIN",
  ASISTENCIAS_LEER: "PERM_ASISTENCIAS_LEER",
  ASISTENCIAS_REGISTRAR: "PERM_ASISTENCIAS_REGISTRAR",
  PAGOS_LEER: "PERM_PAGOS_LEER",
  CAJA_LEER: "PERM_CAJA_LEER",
  STOCK_LEER: "PERM_STOCK_LEER",
  REPORTES_LEER: "PERM_REPORTES_LEER",
  REPORTES_EXPORTAR: "PERM_REPORTES_EXPORTAR",
  CONFIG_LEER: "PERM_CONFIG_LEER",
  CONFIG_ADMIN: "PERM_CONFIG_ADMIN",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
